<h1>Lista grupos</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Nombre</th>
            <th>Activo</th>
            <th>Orden</th>
            <th>acciones</th>            
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($this->lista_menu) > 0) {
            foreach ($this->lista_menu as $indice => $menu) {
                ?>
                <tr id="grupo_<?php echo $menu['id'] ?>">
                    <td></td>
                    <td><?php echo intval($indice+1, 10) ?></td>
                    <td><?php echo $menu['chr_nombre_publico'] ?></td>
                    <td><?php echo intval($menu['bool_active'], 10) ?></td>
                    <td><?php echo intval($menu['int_order'], 10) ?></td>
                    <td><a href="grupo/editar/<?php echo $menu['id'] ?>">Editar</a>&nbsp;|&nbsp;<a href="#" onclick="delete_grupo(<?php echo $menu['id'] ?>);return false;">Eliminar</a></td>
                </tr>
                <?php
            }
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7"></td>
        </tr>
    </tfoot>
</table>