<?php

$form = $this->form;
$form->prepare();

//$form->setAttribute('action', $this->url('seguridad/Index/recibe'));
//$form->setAttribute('method', 'post');
$form->setAttributes(array(
    //'action' => '/seguridad/index/validate',
    'action' => '',
    'method' => 'post',
    'class' => 'form-horizontal'
));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
?>
 <fieldset>
<legend><?php echo $this->title ?></legend>
<div class="control-group">
    <?php
    $chr_nombre = $form->get('chr_nombre');
    $chr_nombre->setValue($this->objUser->chr_nombre);
    
    echo $this->formLabel($form->get('chr_nombre')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_nombre->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_nombre);
    echo $this->formElementErrors($chr_nombre);
    echo '</div>';
    ?>    
</div>
<div class="control-group">
    <?php
    $chr_apellido_paterno = $form->get('chr_apellido_paterno');
    $chr_apellido_paterno->setValue($this->objUser->chr_apellido_paterno);
    
    echo $this->formLabel($form->get('chr_apellido_paterno')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_apellido_paterno);
    echo $this->formElementErrors($chr_apellido_paterno);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $chr_apellido_materno = $form->get('chr_apellido_materno');
    $chr_apellido_materno->setValue($this->objUser->chr_apellido_materno);
    
    echo $this->formLabel($form->get('chr_apellido_materno')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_apellido_materno);
    echo $this->formElementErrors($chr_apellido_materno);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $chr_dni = $form->get('chr_dni');
    $chr_dni->setValue($this->objUser->chr_dni);
    
    echo $this->formLabel($form->get('chr_dni')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_dni);
    echo $this->formElementErrors($chr_dni);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $chr_telefono = $form->get('chr_telefono');
    $chr_telefono->setValue($this->objUser->chr_telefono);
    
    echo $this->formLabel($form->get('chr_telefono')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_telefono);
    echo $this->formElementErrors($chr_telefono);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $chr_domicilio = $form->get('chr_domicilio');
    $chr_domicilio->setValue($this->objUser->chr_domicilio);
    
    echo $this->formLabel($form->get('chr_domicilio')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_domicilio);
    echo $this->formElementErrors($chr_domicilio);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $chr_email = $form->get('chr_email');
    $chr_email->setValue($this->objUser->chr_email);
    
    echo $this->formLabel($form->get('chr_email')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_apellido_paterno->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_email);
    echo $this->formElementErrors($chr_email);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $bool_active = $form->get('bool_active');
    if($this->objUser->bool_active){
        $bool_active->setAttribute('checked','checked');
    }
    echo $this->formLabel($form->get('bool_active')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$bool_active->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($bool_active);
    echo $this->formElementErrors($bool_active);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $btnSubmit = $form->get('btnSubmit');
    //echo $formLabel->openTag().$email->getOption('label');
    echo '<div class="controls">';
    echo $this->formInput($btnSubmit);
    echo '</div>';
    //echo $formLabel->closeTag();
    ?>
</div>
<?php 
    echo $this->formHidden($form->get('csrf'));
    //echo $this->formElementErrors($form->get('csrf'));
?>
<?php
    $idHidden = $form->get('id');
    $idHidden->setValue($this->objUser->id);
    echo $this->formInput($idHidden);
?>
 </fieldset>
<?php echo $this->form()->closeTag(); ?>
<?php
    if($this->message){
        echo $this->message;
    }
?>