<h1>Lista usuarios</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Nombre</th>
            <th>E-mail</th>
            <th>Activo</th>
            <th>acciones</th>            
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($this->userList) > 0) {
            foreach ($this->userList as $indice => $user) {
                ?>
                <tr id="user_<?php echo $user['id'] ?>">
                    <td></td>
                    <td><?php echo intval($indice+1, 10) ?></td>
                    <td><?php echo $user['chr_nombre'].' '.$user['chr_apellido_paterno'] ?></td>
                    <td><?php echo $user['chr_email'] ?></td>
                    <td><?php echo intval($user['bool_active'], 10) ?></td>
                    <td><a href="usuario/editar/<?php echo $user['id'] ?>">Editar</a>&nbsp;|&nbsp;<a href="#" onclick="delete_user(<?php echo $user['id'] ?>);return false;">Eliminar</a></td>
                </tr>
                <?php
            }
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7"></td>
        </tr>
    </tfoot>
</table>