<h3>Lista de accesos por grupo</h3>
<hr />
<p>
  <button class="btn btn-large btn-primary btnSaveAccess" type="button">Guardar</button>
</p>
<ul class="nav nav-tabs nav-stacked">
   <?php 
   foreach ($this->listAccess as $index=>$module): ?>
    <li>
        <a href="#"><?php echo $module['chr_nombre_publico'] ?></a>
        <?php if(count($module['menu'])>0): ?>
            <?php foreach($module['menu'] as $indice=>$menu):?>
                <ul class="nav nav-tabs nav-stacked">
                    <li style="margin-left:20px;">
                        <a href="#"><?php echo $menu['chr_nombre'] ?></a>
                        <?php if(count($menu['submenu'])>0): ?>
                        <table class="table">
                            <?php foreach($menu['submenu'] as $puntero=>$submenu):?>
                            <tr>
                                <td><?php echo $submenu['chr_nombre'] ?></td>
                                <td><input name="chkAccess" type="checkbox" class="style2" <?php echo ($submenu['access'] )?'checked="checked"':'' ?> value="<?php echo $submenu['id'] ?>" /></td>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                        <?php endif; ?>
                    </li>
                </ul>
            <?php endforeach; ?>
        <?php endif; ?>
    </li> 
   <?php endforeach; ?>
</ul>
<p>
  <button class="btn btn-large btn-primary btnSaveAccess" type="button">Guardar</button>
  <input type="hidden" name="grupo_id" id="grupo_id" value="<?php echo $this->grupo_id ?>" />
</p>