<form id="form-search-group" class="form-search-group" action="" method="POST" onsubmit="return false;">
    <fieldset>
        <legend>Acceso de grupos</legend>
        <input name="txtSearch" id="txtSearch" type="text" placeholder="buscar grupo">
        <button type="submit" class="btn">Buscar</button>
    </fieldset>
</form>
<hr />
<div id="divResultado">
    <?php 
    $list = array("listGroup"=>$this->listGroup);
    echo $this->partial('acceso/grupos.phtml',$list); ?>
</div>