<form id="form-search-user" class="form-search-user" action="" method="POST" onsubmit="return false;">
    <fieldset>
        <legend>Acceso de usuarios</legend>
        <input name="txtSearch" id="txtSearch" type="text" placeholder="buscar usuario">
        <button type="submit" class="btn">Buscar</button>
    </fieldset>
</form>
<hr />
<div id="divResultado"><?php
$model = array(
    array('key' => 'Mammal', 'value' => 'Camel'),
    array('key' => 'Bird', 'value' => 'Penguin'),
    array('key' => 'Reptile', 'value' => 'Asp'),
    array('key' => 'Fish', 'value' => 'Flounder'),
);
//var_dump($this->partial('acceso/usuarios.phtml',$model)); ?></div>