<h1>Lista submenús</h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Nombre</th>
            <th>Activo</th>
            <th>Menú</th>
            <th>Módulo</th>
            <th>Orden</th>
            <th>acciones</th>            
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($this->lista_submenu) > 0) {
            foreach ($this->lista_submenu as $indice => $submenu) {
                ?>
                <tr id="submenu_<?php echo $submenu['id'] ?>">
                    <td></td>
                    <td><?php echo intval($indice+1, 10) ?></td>
                    <td><?php echo $submenu['chr_nombre'] ?></td>
                    <td><?php echo intval($submenu['bool_active'], 10) ?></td>
                    <td><?php echo $submenu['chr_nombre_menu'] ?></td>
                    <td><?php echo $submenu['chr_nombre_modulo'] ?></td>
                    <td><?php echo intval($submenu['int_order'], 10) ?></td>
                    <td><a href="submenus/editar/<?php echo $submenu['id'] ?>">Editar</a>&nbsp;|&nbsp;<a href="#" onclick="delete_submenu(<?php echo $submenu['id'] ?>);return false;">Eliminar</a></td>
                </tr>
                <?php
            }
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="8"></td>
        </tr>
    </tfoot>
</table>