<?php

$form = $this->form;
$form->prepare();

//$form->setAttribute('action', $this->url('seguridad/Index/recibe'));
//$form->setAttribute('method', 'post');
$form->setAttributes(array(
    //'action' => '/seguridad/index/validate',
    'action' => '',
    'method' => 'post',
    'class' => 'form-horizontal'
));

$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
?>
 <fieldset>
<legend><?php echo $this->title ?></legend>
<div class="control-group">
    <?php
    $chr_nombre = $form->get('chr_nombre');
    $chr_nombre->setValue($this->objModule->chr_nombre);
    
    echo $this->formLabel($form->get('chr_nombre')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_nombre->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_nombre);
    echo $this->formElementErrors($chr_nombre);
    echo '</div>';
    ?>    
</div>
<div class="control-group">
    <?php
    $chr_nombre_publico = $form->get('chr_nombre_publico');
    $chr_nombre_publico->setValue($this->objModule->chr_nombre_publico);
    
    echo $this->formLabel($form->get('chr_nombre_publico')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$chr_nombre_publico->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($chr_nombre_publico);
    echo $this->formElementErrors($chr_nombre_publico);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $int_order = $form->get('int_order');
    $int_order->setValue($this->objModule->int_order);
    
    echo $this->formLabel($form->get('int_order')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$int_order->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($int_order);
    echo $this->formElementErrors($int_order);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $bool_active = $form->get('bool_active');
    if($this->objModule->bool_active){
        $bool_active->setAttribute('checked','checked');
    }
    echo $this->formLabel($form->get('bool_active')->setLabelAttributes(array('class'=>'control-label')));
    //echo $formLabel->openTag().$bool_active->getOption('label');
    //echo $formLabel->closeTag();
    echo '<div class="controls">';
    echo $this->formInput($bool_active);
    echo $this->formElementErrors($bool_active);
    echo '</div>';
    ?>
</div>
<div class="control-group">
    <?php
    $btnSubmit = $form->get('btnSubmit');
    //echo $formLabel->openTag().$email->getOption('label');
    echo '<div class="controls">';
    echo $this->formInput($btnSubmit);
    echo '</div>';
    //echo $formLabel->closeTag();
    ?>
</div>
<?php 
    echo $this->formHidden($form->get('csrf'));
    //echo $this->formElementErrors($form->get('csrf'));
?>
<?php
    $idHidden = $form->get('id');
    $idHidden->setValue($this->objModule->id);
    echo $this->formInput($idHidden);
?>
 </fieldset>
<?php echo $this->form()->closeTag(); ?>
<?php
    if($this->message){
        echo $this->message;
    }
?>