
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th></th>
            <th>#</th>
            <th>Nombre</th>
            <th>Nombre público</th>
            <th>Activo</th>
            <th>acciones</th>            
        </tr>
    </thead>
    <tbody>
        <?php
        if (count($this->listUser) > 0) {
            foreach ($this->listUser as $indice => $user) {
                ?>
                <tr id="user_<?php echo $user['id'] ?>">
                    <td></td>
                    <td><?php echo intval($indice+1, 10) ?></td>
                    <td><?php echo $user['chr_nombre'] ?></td>
                    <td><?php echo $user['chr_apellido_paterno'] ?></td>
                    <td><?php echo intval($user['bool_active'], 10) ?></td>
                    <td><a href="#">Quitar</a></td>
                </tr>
                <?php
            }
        }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="7"></td>
        </tr>
    </tfoot>
</table>